ToDoApp_MVC/Controllers/HomeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoApp_MVC.Models;
using ToDoApp_MVC.Models.ViewModel;

namespace ToDoApp_MVC.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		private readonly IToDoRepository repository;

		public HomeController(IToDoRepository repo)
		{
			repository = repo;
		}

		[HttpGet]
		[Route("/")]
		public IActionResult Index()
		{
			ViewData["Title"] = "Index";
			ViewBag.IsIndex = true;


			DateTime endOfTheDay = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59);
			DateTime endOfNext7Days = DateTime.Now.AddDays(7);

			var userLists = repository.GetUserToDoLists(this.User);

			var hiddenLists = userLists.Where(l => l.Hidden);
			var toDoLists = userLists.Except(hiddenLists);

			var tasksWithDueTime = toDoLists
				.SelectMany(l => l.Entries)
				.Where(t => t.HasDueTime)
				.OrderBy(t => t.Progress)
				.ThenBy(t => t.DueTime);

			IndexViewModel model = new IndexViewModel
			{
				ToDoLists = toDoLists,
				HiddenLists = hiddenLists,
				TasksForToday = tasksWithDueTime.Where(t => t.DueTime < endOfTheDay)
			};
			model.TasksForNext7Days = tasksWithDueTime.Except(model.TasksForToday).Where(t => t.DueTime < endOfNext7Days);

			return View(model);
		}
	}
}

ToDoApp_MVC/Controllers/ListController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ToDoApp.DomainLibrary;
using ToDoApp_MVC.Models;
using ToDoApp_MVC.Models.ViewModel;

namespace ToDoApp_MVC.Controllers
{
	[Authorize]
	[Route("/[controller]/[action]")]
	public class ListController : Controller
	{
		private readonly IToDoRepository repository;

		public ListController(IToDoRepository repo)
		{
			repository = repo;
		}

		[HttpGet]
		public IActionResult New()
		{
			ViewData["Title"] = "New list";
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> New(ToDoListViewModel model)
		{
			ViewData["Title"] = "New list";

			if (ModelState.IsValid)
			{
				ToDoUser currentUser = await repository.GetUserAsync(this.User);

				if (currentUser is null)
				{
					return StatusCode(StatusCodes.Status500InternalServerError);
				}

				ToDoList toDoList = new ToDoList()
				{
					Title = model.Title,
					Description = model.Description,
					CreationTime = DateTime.Now,
					Author = currentUser
				};

				await repository.AddAsync(toDoList);

				return RedirectToAction(actionName: "Index", controllerName: "Home");
			}

			return View(model);
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Edit(int id)
		{
			ViewData["Title"] = "Edit list";
			ViewBag.IsEdit = true;

			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null)
			{
				return NotFound();
			}

			ToDoListViewModel model = new ToDoListViewModel()
			{
				Title = list.Title,
				Description = list.Description
			};

			return View("New", model);
		}

		[HttpPost("{id}")]
		public async Task<IActionResult> Edit(int id, [FromForm] ToDoListViewModel listModel)
		{
			ViewData["Title"] = "Edit list";

			if (ModelState.IsValid)
			{
				ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

				if (list is null)
				{
					return NotFound();
				}

				list.Title = listModel.Title;
				list.Description = listModel.Description;

				await repository.UpdateAsync(list);

				return RedirectToAction(actionName: "Index", controllerName: "Home");
			}

			return View("New", listModel);
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Delete(int id)
		{
			ViewData["Title"] = "Delete list";

			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null) { return NotFound(); }

			return View(list);
		}

		[HttpPost("{id}")]
		public async Task<IActionResult> Delete(int id, [FromForm] int listId)
		{
			if (id != listId)
			{
				return BadRequest();
			}

			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null)
			{
				return NotFound();
			}

			await repository.DeleteAsync(list);

			return RedirectToAction(actionName: "Index", controllerName: "Home");
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Hide(int id)
		{
			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null)
			{
				return NotFound();
			}

			list.Hidden = true;
			await repository.SaveChangesAsync();

			return RedirectToAction(actionName: "Index", controllerName: "Home");
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> UnHide(int id)
		{
			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null)
			{
				return NotFound();
			}

			list.Hidden = false;
			await repository.SaveChangesAsync();

			return RedirectToAction(actionName: "Index", controllerName: "Home");
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Copy(int id)
		{
			ViewData["Title"] = "Copy list";
			ViewBag.IsCopy = true;

			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list is null)
			{
				return NotFound();
			}

			ToDoListViewModel model = new ToDoListViewModel()
			{
				Title = list.Title,
				Description = list.Description
			};

			return View("New", model);
		}

		[HttpPost("{id}")]
		public async Task<IActionResult> Copy(int id, ToDoListViewModel model)
		{
			if (ModelState.IsValid)
			{
				ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id, includeEntries: true);

				if (list is null)
				{
					return NotFound();
				}

				ToDoList newList = new ToDoList()
				{
					Title = model.Title,
					Description = model.Description,
					CreationTime = DateTime.Now,
					Author = list.Author,
					Hidden = list.Hidden
				};

				repository.Update(newList);

				foreach (var task in list.Entries)
				{
					newList.Entries.Add(new ToDoEntry
					{
						Title = task.Title,
						Description = task.Description,
						CreationTime = DateTime.Now,
						HasDueTime = task.HasDueTime,
						DueTime = task.DueTime,
						Progress = task.Progress,
						ToDoListId = newList.Id
					});
				}

				await repository.SaveChangesAsync();

				return RedirectToAction(actionName: "Index", controllerName: "Home");
			}

			return View("New", model);
		}
	}
}

ToDoApp_MVC/Controllers/TaskController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoApp.DomainLibrary;
using ToDoApp_MVC.Models;
using ToDoApp_MVC.Models.ViewModel;

namespace ToDoApp_MVC.Controllers
{
	[Authorize]
	[Route("/[controller]/[action]")]
	public class TaskController : Controller
	{
		private readonly IToDoRepository repository;

		public TaskController(IToDoRepository repo)
		{
			repository = repo;
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> New(int id)
		{
			ViewData["Title"] = "Create Task";

			ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

			if (list == null)
			{
				return BadRequest();
			}

			ToDoEntryViewModel model = new ToDoEntryViewModel();
			model.DueTime = DateTime.Now.AddDays(1);

			return View(model);
		}

		[HttpPost("{id}")]
		public async Task<IActionResult> New(int id, ToDoEntryViewModel model)
		{
			ViewData["Title"] = "Create Task";

			if (ModelState.IsValid)
			{
				ToDoList list = await repository.GetUserToDoListByIdAsync(this.User, id);

				if (list == null)
				{
					return BadRequest();
				}

				ToDoEntry entry = new ToDoEntry()
				{
					Title = model.Title,
					Description = model.Description,
					HasDueTime = model.HasDueTime,
					ToDoListId = list.Id
				};
				if (model.HasDueTime)
					entry.DueTime = model.DueTime;

				list.Entries.Add(entry);

				await repository.UpdateAsync(list);

				return RedirectToAction(actionName: "Index", controllerName: "Home");
			}

			return View(model);
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Edit(int id)
		{
			ViewData["Title"] = "Edit Task";
			ViewBag.IsEdit = true;

			ToDoEntry task = await repository.GetUserToDoEntryByIdAsync(this.User, id);

			if (task is null)
			{
				return NotFound();
			}

			ToDoEntryViewModel model = new ToDoEntryViewModel()
			{
				Title = task.Title,
				Description = task.Description,
				HasDueTime = task.HasDueTime
			};
			if (task.HasDueTime)
				model.DueTime = task.DueTime;

			return View("New", model);
		}

		[HttpPost("{id}")]
		public async Task<IActionResult> Edit(int id, [FromForm] ToDoEntryViewModel model)
		{
			ViewData["Title"] = "Edit Task";
			ViewBag.IsEdit = true;

			ToDoEntry task = await repository.GetUserToDoEntryByIdAsync(this.User, id);

			if (ModelState.IsValid)
			{
				if (task is null)
				{
					return NotFound();
				}

				task.Title = model.Title;
				task.Description = model.Description;
				task.HasDueTime = model.HasDueTime;
				if (model.HasDueTime)
				{
					task.DueTime = model.DueTime;
				}

				await repository.UpdateAsync(task);

				return RedirectToAction(actionName: "Index", controllerName: "Home");
			}

			model.Title = task.Title;

			return View("New", model);
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Delete(int id)
		{
			ToDoEntry task = await repository.GetUserToDoEntryByIdAsync(this.User, id);

			if (task is null)
			{
				return NotFound();
			}

			await repository.DeleteAsync(task);

			return RedirectToAction(actionName: "Index", controllerName: "Home");
		}

		[HttpGet("{id}")]
		public async Task<IActionResult> Progress(int id, ToDoProgress newProgress)
		{
			ToDoEntry task = await repository.GetUserToDoEntryByIdAsync(this.User, id);

			if (task is null)
			{
				return NotFound();
			}

			task.Progress = newProgress;
			await repository.UpdateAsync(task);

			return RedirectToAction(actionName: "Index", controllerName: "Home");
		}
	}
}

ToDoApp_MVC/Views/Home/Index.cshtml
@model IndexViewModel


<ul class="list-group">
	<li class="list-unstyled list-group list-group-item mb-4 pt-4">
		<h4>
			<span>For Today</span>
			<i class="bi bi-calendar4-event"></i>
		</h4>
		@if (Model.TasksForToday.Count() == 0)
		{
			<p class="ms-4 mt-4 text-muted">There is no task for today.</p>
		}
		else
		{
			<div class="list-group mt-4 mb-2">
				@foreach (var task in Model.TasksForToday)
				{
					<a class="list-group-item list-group-item-action" href=@($"#task{task.Id}")>
						@switch (task.Progress)
						{
							case ToDoProgress.NotStarted:
								<i class="bi bi-circle text-danger"></i>
								break;

							case ToDoProgress.InProgress:
								<i class="bi bi-stopwatch text-info" style="font-size: 1.2rem; line-height: 1.2"></i>
								break;

							case ToDoProgress.Completed:
								<i class="bi bi-check2-circle text-success" style="font-size: 1.2rem; line-height: 1.3"></i>
								break;
						}
						<span>@task.Title</span>
						@if (task.Progress != ToDoProgress.Completed)
						{
							@if (task.DueTime < DateTime.Now)
							{
								<p class="small m-0 ps-4 text-danger" style="font-size: 0.8rem">Deadline exceeded</p>
							}
							else
							{
								<p class="small m-0 ps-4 text-muted" style="font-size: 0.8rem">
									@(
										(task.DueTime - DateTime.Now).Hours
										) hours left
								</p>
							}
						}
					</a>
				}
			</div>
		}
	</li>
	<li class="list-unstyled list-group list-group-item mb-4 pt-4">
		<h4>
			<span>Next 7 days</span>
			<i class="bi bi-calendar4-event"></i>
		</h4>
		@if (Model.TasksForNext7Days.Count() == 0)
		{
			<p class="ms-4 mt-4 text-muted">There are no tasks for the next week.</p>
		}
		else
		{
			<div class="list-group mt-4 mb-2">
				@foreach (var task in Model.TasksForNext7Days)
				{
					<a class="list-group-item list-group-item-action" href=@($"#task{task.Id}")>
						@switch (task.Progress)
						{
							case ToDoProgress.NotStarted:
								<i class="bi bi-circle text-danger"></i>
								break;

							case ToDoProgress.InProgress:
								<i class="bi bi-stopwatch text-info" style="font-size: 1.2rem; line-height: 1.2"></i>
								break;

							case ToDoProgress.Completed:
								<i class="bi bi-check2-circle text-success" style="font-size: 1.2rem; line-height: 1.3"></i>
								break;
						}
						<span>@task.Title</span>
						@if (task.Progress != ToDoProgress.Completed)
						{
							<p class="small m-0 ps-4 text-muted" style="font-size: 0.8rem">
								@((task.DueTime - DateTime.Now).Days) days and @((task.DueTime - DateTime.Now).Hours) hours left
							</p>
						}
					</a>
				}
			</div>
		}
		<ul class="list-group">
		</ul>
	</li>
	@foreach (var todo in Model.ToDoLists)
	{
		<li class="list-unstyled list-group list-group-item mb-4 pt-4">
			<h4>
				<b>@todo.Title</b>
			</h4>
			<p class="small">Created: <time>@todo.CreationTime</time></p>
			<div>
				<a class="btn btn-outline-primary" asp-action="New" asp-controller="Task" asp-route-id="@todo.Id">Add task</a>
				<a class="btn btn-outline-secondary" asp-action="Edit" asp-controller="List" asp-route-id="@todo.Id">
					<i class="bi bi-pen"></i>
				</a>
				<a class="btn btn-outline-secondary" asp-action="Copy" asp-controller="List" asp-route-id="@todo.Id">
					<i class="bi bi-files"></i>
				</a>
				<a class="btn btn-outline-secondary" asp-action="Hide" asp-controller="List" asp-route-id="@todo.Id">
					<i class="bi bi-eye-slash"></i>
				</a>
				<a class="btn btn-outline-danger" asp-action="Delete" asp-controller="List" asp-route-id="@todo.Id">
					<i class="bi bi-trash"></i>
				</a>
			</div>
			<p class="my-3">@todo.Description</p>
			<ul class="list-group">
				@foreach (var task in todo.Entries)
				{
					<li class="list-group-item pt-3" id=@($"task{task.Id}")>
						<div class="d-flex flex-row">
							<p class="me-3 mb-0">
								@switch (task.Progress)
								{
									case ToDoProgress.NotStarted:
										<i class="bi bi-circle text-danger"></i>
										break;

									case ToDoProgress.InProgress:
										<i class="bi bi-stopwatch text-info" style="font-size: 1.2rem; line-height: 1.2"></i>
										break;

									case ToDoProgress.Completed:
										<i class="bi bi-check2-circle text-success" style="font-size: 1.2rem; line-height: 1.3"></i>
										break;
								}
							</p>
							<h5 class="mb-0">@task.Title</h5>
						</div>

						<table class="small my-2 ml-3">
							<tr>
								<td class="pe-3">Added:</td>
								<td>@task.CreationTime</td>
							</tr>
							@if (task.HasDueTime)
							{
								<tr>
									<td class="pe-3">Due Time:</td>
									<td class="text-danger">@task.DueTime</td>
								</tr>
							}
						</table>

						<div class="ml-3">
							<div class="dropdown d-inline-block">
								<a class="btn btn-outline-info btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
									Mark as
								</a>

								<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
									@if (task.Progress != ToDoProgress.NotStarted)
									{
										<a class="dropdown-item" asp-action="Progress" asp-controller="Task" asp-route-id="@task.Id" asp-route-newProgress="@ToDoProgress.NotStarted">Not Started</a>
									}

									@if (task.Progress != ToDoProgress.InProgress)
									{
										<a class="dropdown-item" asp-action="Progress" asp-controller="Task" asp-route-id="@task.Id" asp-route-newProgress="@ToDoProgress.InProgress">In Progress</a>
									}

									@if (task.Progress != ToDoProgress.Completed)
									{
										<a class="dropdown-item" asp-action="Progress" asp-controller="Task" asp-route-id="@task.Id" asp-route-newProgress="@ToDoProgress.Completed">Completed</a>
									}
								</div>
							</div>
							<a class="btn btn-outline-secondary btn-sm" asp-controller="Task" asp-action="Edit" asp-route-id="@task.Id">
								<i class="bi bi-pen"></i>
							</a>
							<a class="btn btn-outline-danger btn-sm" asp-controller="Task" asp-action="Delete" asp-route-id="@task.Id">
								<i class="bi bi-trash"></i>
							</a>
						</div>

						<p class="my-2">@task.Description</p>
					</li>
				}
			</ul>
		</li>
	}
	<li class="list-unstyled list-group list-group-item mt-5 mb-4 pt-4">
		<h4>
			Hidden Lists
			<i class="bi bi-eye-slash"></i>
		</h4>
		@if (Model.HiddenLists.Count() == 0)
		{
			<p class="ms-4 mt-4 text-muted">There are no hidden lists.</p>
		}
		else
		{
			<div class="list-group mt-4 mb-2">
				@foreach (var todo in Model.HiddenLists)
				{
					<a class="list-group-item list-group-item-action" asp-action="Unhide" asp-controller="List" asp-route-id="@todo.Id">
						<i class="bi bi-eye"></i>
						<span>@todo.Title</span>
					</a>
				}
			</div>
		}
	</li>
</ul>